// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTKDvJPt8SsQM8QlblmdqIAofT3cF1v0',
    appId: '1:860080885808:web:fe43bfa8f7baa1aa389df5',
    messagingSenderId: '860080885808',
    projectId: 'atesur-app-v4',
    authDomain: 'atesur-app-v4.firebaseapp.com',
    storageBucket: 'atesur-app-v4.firebasestorage.app',
    measurementId: 'G-PCB7NF1VWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6j4LD-n_xHlVmCTVWHNrH2XThTFTtGxg',
    appId: '1:860080885808:android:47432ef43899a898389df5',
    messagingSenderId: '860080885808',
    projectId: 'atesur-app-v4',
    storageBucket: 'atesur-app-v4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsSlqJ03hirIgfEgaZqeCtbKQ3O8ZXnI',
    appId: '1:860080885808:ios:a8b89a52991eeecd389df5',
    messagingSenderId: '860080885808',
    projectId: 'atesur-app-v4',
    storageBucket: 'atesur-app-v4.firebasestorage.app',
    iosBundleId: 'com.atesur.atesurAppV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsSlqJ03hirIgfEgaZqeCtbKQ3O8ZXnI',
    appId: '1:860080885808:ios:e46e0fe737b5a8c2389df5',
    messagingSenderId: '860080885808',
    projectId: 'atesur-app-v4',
    storageBucket: 'atesur-app-v4.firebasestorage.app',
    iosBundleId: 'com.e2y.atesurapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHTKDvJPt8SsQM8QlblmdqIAofT3cF1v0',
    appId: '1:860080885808:web:97cfb210c312000e389df5',
    messagingSenderId: '860080885808',
    projectId: 'atesur-app-v4',
    authDomain: 'atesur-app-v4.firebaseapp.com',
    storageBucket: 'atesur-app-v4.firebasestorage.app',
    measurementId: 'G-EQNTFWS1P9',
  );
}
